pipeline:
    name: payment-service
    identifier: paymentservice
    allowStageExecutions: false
    projectIdentifier: HarnessBootcamp
    orgIdentifier: BootcampOrg
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: BootcampGitHubConnector
                repoName: harness-cie-lab
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.bootcampgkecluster
                          namespace: build-ns
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                name: bootcamp-dockerhub
                                identifier: bootcampdockerhub
                                spec:
                                    connectorRef: account.bootcampdockerhub
                                    image: nikpap/mvn-openjdk-8:harness
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    packages: com.nikp
                                    runOnlySelectedTests: true
                                description: runTestsWithIntelligence
